[package]
name = "shared_parser"
version = "0.1.0"
authors = ["proecho <niamhgillespie2016@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objects = {path = "../objects"}
chrono = "0.4"
